### ISSUE TITLE
Scope & project

### ISSUE THREAD

**Issue by rafaelimao** [rafaelimao/pacman#11]
**Main Idea:** Get the core mechanics from Pacman and implement them in a puzzle-focused top-down stealth game.

# Tasks

- [ ] Getting the core mechanics down
    - [X] Player
    - [ ] Ghosts
    - [ ] Powerup
- [ ] Getting puzzle mechanics down
    - [ ] Buttons
    - [ ] Levers
    - [ ] Boxes
    - [ ] Doors
    - [ ] Timers
- [ ] Getting a level editor
    - [ ] **WIP: **Figure out how to do this
- [ ] Getting the levels
    - [ ] **WIP: **Depends on the level editor
- [ ] Polish
    - [ ] **WIP: **It's polish, it's only defined at the end.
